AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 Instance using cloud formation"

Parameters: 
  serverType:
    Description: "EC2 Server Type"
    Type: "String"
    Default: "linuxServer"
    AllowedValues:
      - "linuxServer"
      - "linuxWebServer"
  instanceType:
    Description: "EC2 Instance Type"
    Type: "String"
    Default: "t3.micro"
    AllowedValues:
      - "t3.micro"
      - "t3.small"
  vpcId:
    Description: "VPC ID"
    Type: "String"
    Default: "vpc-0d95196e9a48a27b0"
  keyPairName:
    Description: "EC2 KeyPair Name"
    Type: "String"
    Default: "aws-trm-2025"

Mappings:
  ec2AMI:
    "linuxServer":
      amiId: "ami-0341d95f75f311023"
      # SecurityGroupIds: !GetAtt ec2LinuxWebSecGroup.GroupId
    "linuxWebServer":
      amiId: "ami-01906a33c34438ac8"
      # SecurityGroupIds: !GetAtt ec2LinuxSecGroup.GroupId

Conditions:
  isLinuxWebServer: !Equals [!Ref serverType, "linuxWebServer"]

Resources: 
  ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings: 
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: 8
      ImageId: !FindInMap [ec2AMI, !Ref serverType, amiId]
      InstanceType: !Ref instanceType
      KeyName: !Ref keyPairName
      SecurityGroupIds: !If
        - isLinuxWebServer
        - [!GetAtt ec2LinuxSecGroup.GroupId, !GetAtt ec2LinuxWebSecGroup.GroupId]
        - [!GetAtt ec2LinuxSecGroup.GroupId]



  ec2LinuxSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "CFN Linux Server Security Group"
      GroupName: "cfnLinuxSec"
      SecurityGroupEgress: 
        - CidrIp: "0.0.0.0/0"
          Description: "Allow All Outbound"
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress: 
        - CidrIp: "0.0.0.0/0"
          Description: "Allow SSH"
          FromPort: 22
          IpProtocol: "tcp"
          ToPort: 22
      VpcId: !Ref vpcId #secgroup -> VPC ID

  ec2LinuxWebSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "CFN Linux Web Server Security Group"
      GroupName: "cfnLinuxWebSec"
      SecurityGroupEgress: 
        - CidrIp: "0.0.0.0/0"
          Description: "Allow All Outbound"
          FromPort: -1
          IpProtocol: -1
          ToPort: -1
      SecurityGroupIngress: 
        - CidrIp: "0.0.0.0/0"
          Description: "Allow HTTP"
          FromPort: 80
          IpProtocol: "tcp"
          ToPort: 80
      VpcId: !Ref vpcId