AWSTemplateFormatVersion: 2010-09-09
Description: "Sample Lambda Function using CFN"

Parameters:
  functionName:
    Description: "Name of the Lambda Function"
    Type: "String"
    Default: "fnHelloWorldCfn"
  s3Bucket:
    Description: "S3 bucket of the lambda function"
    Type: "String"
    Default: "ysm-trn-cfn-scripts"
  lambdaZipFile:
    Description: "Zip file path of the lambda function in S3"
    Type: "String"
    Default: "helloWorld.zip"
  lambdaHandler:
    Description: "Handler of the lambda function"
    Type: "String"
    Default: "s3_lambda.handler"
  

Resources: 
  myLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref s3Bucket                              # bucket name
        S3Key: !Join ["/", ["lambda", !Ref lambdaZipFile]]   # path of the zipped lambda
      Description: "Sample Lambda using CFN"                 # description of the lambda
      FunctionName: !Ref functionName                        # name of lambda
      Handler: !Ref lambdaHandler                             # fileName.functionName
      Role: !GetAtt lambdaFunctionRole.Arn                   # arn of the role
      Runtime: "python3.12"                                  # language to use 
      Timeout: 60                                            # default is 3 seconds





  # ====================================
  # DYNAMIC LAMBDA ROLE
  # ====================================
  lambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: !Join [" ", ["IAM Role for ", !Ref functionName, "lambda function"]]
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"           
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      RoleName: !Join ["-", [!Ref functionName, "lambda", "role"]]
      Policies:
        - PolicyName: !Join ["-", [!Ref functionName, "execution", "policy"]]
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - "logs:CreateLogGroup"
                Resource: 
                  - "arn:aws:logs:*:*:*"    
              - Effect: Allow
                Action: 
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: 
                  - !Join ["", ["arn:aws:logs:*:*:log-group:/aws/lambda/", !Ref functionName, ":*"] ]  
  # ====================================
  # DYNAMIC LAMBDA ROLE
  # ====================================